title: Asteria Interactive
email: franz@tanglao.org
description: >- # this means to ignore newlines until "baseurl:"
  Discover comprehensive digital solutions with Asteria Interactive. Specializing in web page creation, applications development, eCommerce solutions, SaaS/PaaS platforms, and CyberSecurity services. Enhance your online presence and secure your digital assets with our expert team. Contact us today!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://asteriainteractive.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fritzdenim
github_username:  franznoel

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      title: Asteria Interactive
      navigation: menu.html


# Build settings
plugins:
  - jekyll-feed
  - jekyll-environment-variables

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
